# yaml-language-server: $schema=./node_modules/harperdb/config-app.schema.json

loadEnv:
  files:
    - '.env'

rest: true

graphqlSchema:
  files: 'schemas/*.graphql'

jsResource:
  files: 'resources/*.js'
